### ISSUE TITLE
4.6 Isnt out yet,

### ISSUE THREAD

**Issue by karbis-alt** [man553/final-ron#5]
### Describe your bug here.

The Bug is. that ron 4.6 isnt out yet
Please fix

### Command Prompt/Terminal logs (if existing)

```bash
source/menus/DesktopMenu.hx:100: characters 6-12 : Warning : Local variable button might be used before being initialized
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I did jackshit

**Comment by BashyBush** [comment]
epoc

**Comment by seezee553** [comment]
hes so good

**Comment by Sword352** [comment]
This is a warning, you can safely ignore it. The local variable `button` hasn't been initialized  right after it's declaration so Haxe warn us that there might be references to it before being actually initialized, which causes a null object reference. If this warning gets annoying, just set the variable to null by default.
Thank you for your patience!
