### ISSUE TITLE
Im not hired for vs ron

### ISSUE THREAD

**Issue by OOF-PRODUCTIONS** [man553/final-ron#7]
### What feature do you want to get added on the **base** engine?

Reasons why I should be hired for vs ron fnf real
1: I'm good corder

2: So cool

3: Can I work on your fnf mod :pleading:

4: Ronald fnf

5: I'm so cool like Ron fnf

6: The voices won't stop

I hope this really helps me get onto the fnf mod known as "Vs Ron"

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by seezee553** [comment]
The voices wont stop
